apiVersion : apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: noisonnoiton/bff:v1
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  labels:
    app: bff
spec:
  ports:
    - port: 80
      targetPort: 8081
      name: bff
  selector:
    app: bff
  type: LoadBalancer
