server:
  port: 8081

spring:
  application:
    name: js-bff-service
  thymeleaf:
    prefix: classpath:/static/html/
  session:
    store-type: redis
#    spring.session.store-type=redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: skcc
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

api:
  account:
    #url: http://apigateway.skcc.co.kr/account
    url: http://localhost:8090/account
  accountbank:
    #url: http://apigateway.skcc.co.kr/accountbank
    url: http://localhost:8090/accountbank
  cart:
    #url: http://apigateway.skcc.co.kr/cart
    url: http://localhost:8090/cart
  category:
    #url: http://apigateway.skcc.co.kr/category
    url: http://localhost:8090/category
  order:
    #url: http://apigateway.skcc.co.kr/order
    url: http://localhost:8090/order
  payment:
    #url: http://apigateway.skcc.co.kr/payment
    url: http://localhost:8090/payment
  product:
    #url: http://apigateway.skcc.co.kr/product
    url: http://localhost:8090/product
