server:
  port: 8081

spring:
  application:
    name: js-bff-service
  thymeleaf:
    prefix: classpath:/static/html/
  session:
    store-type: redis
#    spring.session.store-type=redis
  redis:
    host: 20.194.18.209
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

api:
  account:
    url: http://localhost:8090/account
  accountbank:
    url: http://localhost:8090/accountbank
  cart:
    url: http://localhost:8090/cart
  category:
    url: http://localhost:8090/category
  order:
    url: http://localhost:8090/order
  payment:
    url: http://localhost:8090/payment
  product:
    url: http://localhost:8090/product
